name: Pandas-TA CI

on:
  push:
    branches:
      - main
      - ci/*
    tags:
  pull_request:


concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}-${{ github.event_name }}"
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "ubuntu-22.04", "ubuntu-24.04", "macos-13", "macos-14", "macos-15", "windows-latest" ]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        exclude:
          - os: "macos-14"
            python-version: "3.9"
          - os: "macos-15"
            python-version: "3.9"

          - os: "windows-latest"
            python-version: "3.9"

    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache-dependency-glob: "requirements.txt"
        cache-suffix: "${{ matrix.python-version }}"


    - name: Installation - *nix
      run: |
        uv pip install -r requirements.txt pytest
        uv pip install -e .


    - name: Tests
      run: |
        pytest


  build:
    needs: [ test ]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: 3.11

    - name: Extract branch name
      id: extract-branch
      run: |
        echo "GITHUB_REF='${GITHUB_REF}'"
        echo "branch=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

    - name: Build distribution
      run: |
        pip install -U build
        python -m build --sdist --wheel

    - name: Upload artifacts 📦
      uses: actions/upload-artifact@v4
      with:
        name: ft-pandas-ta
        path: |
          dist
        retention-days: 10
